{
  "formatVersion": "1.1",
  "component": {
    "group": "com.barry.bytecode",
    "module": "ByteCodePlugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "ByteCodePlugin-1.0.0.jar",
          "url": "ByteCodePlugin-1.0.0.jar",
          "size": 7702,
          "sha512": "24f5d377576ba7e8819b1b7944013dac7cc041bd76708348c33881c990d7fe704f5b3e2fbdcc98754a63c8cef1f0bd9d4d439d258eeb973a19587b4091951703",
          "sha256": "fc96a7237fb3cc045959f7bd8f2990a9fd59a4e9280ab506a09da9217eeb3021",
          "sha1": "9d704cfb893528e738e9369e6da367b41f60fdd2",
          "md5": "b88f512bd5829ab30a9370355f82ea70"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.6.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "ByteCodePlugin-1.0.0.jar",
          "url": "ByteCodePlugin-1.0.0.jar",
          "size": 7702,
          "sha512": "24f5d377576ba7e8819b1b7944013dac7cc041bd76708348c33881c990d7fe704f5b3e2fbdcc98754a63c8cef1f0bd9d4d439d258eeb973a19587b4091951703",
          "sha256": "fc96a7237fb3cc045959f7bd8f2990a9fd59a4e9280ab506a09da9217eeb3021",
          "sha1": "9d704cfb893528e738e9369e6da367b41f60fdd2",
          "md5": "b88f512bd5829ab30a9370355f82ea70"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ByteCodePlugin-1.0.0-javadoc.jar",
          "url": "ByteCodePlugin-1.0.0-javadoc.jar",
          "size": 86648,
          "sha512": "63b77161280ee56a0777f5233c7e9d36279ed1e260a5b1fa3ed721a97a2424105f56609b6797e2a33274d1990b446c4ccd232c6c33141e268e6e6edfd4ea08ca",
          "sha256": "93529066e581b172a5ffafcb4978bcd4c1c659e34beec17f397532b4cf25c362",
          "sha1": "be92185b29cd1817febfbf7fae4cfd1a186f62d1",
          "md5": "c81428bdcd8c6f77ad1e2addcf4747b2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ByteCodePlugin-1.0.0-sources.jar",
          "url": "ByteCodePlugin-1.0.0-sources.jar",
          "size": 6742,
          "sha512": "78adca1dae4f465483ca3d7ea2dc56e9f1be0573f120e64a68843d7f20d2ad3ff12526d7ebca541a07ccadec7cd42efdbadcd07c04e47d920826d15c35160de7",
          "sha256": "bdf88c5f4658ab535d48a0f9232218453efddbda3152096634b8377b285ab74d",
          "sha1": "c3657307894ce2f72fe7cf36d424024ef46f99ed",
          "md5": "356046e5bcff606a462c406663d21252"
        }
      ]
    }
  ]
}
