{
  "formatVersion": "1.1",
  "component": {
    "group": "com.barry.bytecode",
    "module": "MyPlugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "MyPlugin-1.0.0.jar",
          "url": "MyPlugin-1.0.0.jar",
          "size": 2028,
          "sha512": "f813035ff33d4fb822f9f7249f03509379fefa6040b84947e1b2ea4c6fdf4d87d942d448e87163486292c9d24c8a4c8000fd3cc576ecc13bd9a072b0e356441f",
          "sha256": "44a31d0b3fbcf0d4563b6a279bd776d85e355d9eea630b164fec6495196d0889",
          "sha1": "0087c159edff81122da3688bbbfa8ca5470466d6",
          "md5": "a10c1ebcb45810262fd6cbbb6ef8dd5c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "MyPlugin-1.0.0.jar",
          "url": "MyPlugin-1.0.0.jar",
          "size": 2028,
          "sha512": "f813035ff33d4fb822f9f7249f03509379fefa6040b84947e1b2ea4c6fdf4d87d942d448e87163486292c9d24c8a4c8000fd3cc576ecc13bd9a072b0e356441f",
          "sha256": "44a31d0b3fbcf0d4563b6a279bd776d85e355d9eea630b164fec6495196d0889",
          "sha1": "0087c159edff81122da3688bbbfa8ca5470466d6",
          "md5": "a10c1ebcb45810262fd6cbbb6ef8dd5c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "MyPlugin-1.0.0-javadoc.jar",
          "url": "MyPlugin-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "d6f6d3671715e97b148d8607dc7953555f39bfb516bce3db8354b15a7823126ec7bbacb1b52360c3b3e3cd87929181c558e4c888e2d0757a497350f9dfb505f0",
          "sha256": "a13b31e26e8a287f68593093e8ab02df379eaa14d8dcccdc23202e97dbbefd5f",
          "sha1": "6360de29418c6e669a1d287cf1195f0a54d32a1c",
          "md5": "caf30468c00c5451d478f8e364e53c29"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "MyPlugin-1.0.0-sources.jar",
          "url": "MyPlugin-1.0.0-sources.jar",
          "size": 888,
          "sha512": "15d4f32fae582651cca10820b9a885d608d20f7891c94148a1dfa30d62c26f9c98d5e63eefcc2341358620ea0964fe27867b01660325ac70d328a75d18d81c3c",
          "sha256": "be054eddbf0352ed558324ce9f12f7ce2fb0af81933264681b796ccc199cecd8",
          "sha1": "282ea6acd74d635a58341e424f22e4d84af13d55",
          "md5": "6bb3047e252ec03422ca4b2e61de811c"
        }
      ]
    }
  ]
}
